name: Deploy VGPS Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}

          script: |
            cd /home/ubuntu/VGPS
            git pull origin main

            cd server
            npm install

            pm2 restart vgps-backend
            pm2 save

            echo "VGPS Backend Deployed Successfully!"